spring:
  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/1810b
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: login_dubbo
  dubbo:
     application:
           name: login_dubbo_provider
     registry:
           address: zookeeper://127.0.0.1:8080
     protocol:
           name: dubbo
           port: 20880
     scan: com.jk.service
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: 1229344414@qq.com
    password: tgeuiwyshhnlfjag
    properties:
       mail:
           smtp:
             auth: true
             starttls:
               enable: true
               required: true


mybatis:
  mapperLocations: classpath*:mybatis/mapper-*.xml
  typeAliasesPackage: com.jk.pojo






data:
  mongodb:
    uri: mongodb://127.0.0.1:27017/1808b



  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000


server:
  port: 8081
